name: Release Extensions Packages

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        
    - name: Package.json info
      uses: rexdefuror/read-package-json@v1.0.5

    - name: Build
      run: |
        npm install
        npm run build
        npm run version
        gulp

    - uses: ncipollo/release-action@v1
      with:
        name : Xtense ${{ env.PACKAGE_VERSION }}
        draft: true
        artifacts: "release/chrome-${{ env.PACKAGE_VERSION }}.zip,release/firefox-${{ env.PACKAGE_VERSION }}.zip,release/edge-${{ env.PACKAGE_VERSION }}.zip"
        artifactContentType: zip
        body : "To be Completed"
        tag : ${{ env.PACKAGE_VERSION }}

